# Generated by Django 3.2.5 on 2024-01-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub_App', '0002_admin_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_sr',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookHub_App.authors')),
            ],
        ),
    ]
