# Generated by Django 3.2.5 on 2024-01-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub_App', '0004_auto_20240128_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books_sr',
        ),
    ]
