# Generated by Django 3.2.5 on 2024-01-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub_App', '0005_delete_books_sr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_name',
            new_name='author',
        ),
    ]
